#:import NoTransition kivy.uix.screenmanager.NoTransition
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import MDDropdownMenu kivymd.uix.menu.MDDropdownMenu

<ScaleLabel@MDLabel>:
	_scale: 1. if self.texture_size[0] < self.width else float(self.width) / self.texture_size[0]
	canvas.before:
		PushMatrix
		Scale:
			origin: self.center
			x: self._scale or 1.
			y: self._scale or 1.
	canvas.after:
		PopMatrix
    font_name:"font//Nunito//Nunito-SemiBold.ttf"

<Button_Create_User_Database@ButtonBehavior+Image>:
    on_press: app.create_user_database()
<Button_Sign_In_Database@ButtonBehavior+Image>:
    on_press: app.sign_in_database()
<Button_Reset_User_Password@ButtonBehavior+Image>:
    on_press: app.open_reset_dialog()
<Button_Sign_Up@ButtonBehavior+Image>:
    on_press: app.sign_up_screen()
<Button_Sign_In@ButtonBehavior+Image>:
    on_press: app.sign_in_screen()
<Button_DB@ButtonBehavior+Image>:
    pos_hint : {'center_x': 0.5 , 'center_y' : 0.5} 
<Button_DB_Log_Out@ButtonBehavior+Image>:
    pos_hint : {'center_x': 0.5 , 'center_y' : 0.5} 
ScreenManager:
    WelcomeScreen:
    SignInScreen:
    CreateUserScreen:
    DashBoardScreen:
    ResetPasswordScreen:
<WelcomeScreen>
    name : 'welcomescreen'
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'img//bg_login_v1.png'
    orientation : 'vertical'
    MDBoxLayout:
        orientation : 'vertical'
        MDBoxLayout:
            size_hint_y : 0.08
            # md_bg_color: 255/255, 255/255, 255/255, 1
            Widget:
                size_hint_x : 0.1
            Image:
                source : 'logo//logo_long_full_white.png'
                size_hint_x : 1.2
            Widget:
                size_hint_x : 4.2
            ScaleLabel:
                text : 'TRANG CHỦ'
                color : 255/255, 255/255, 255/255, 1
                font_size : self.height * 0.25
            ScaleLabel:
                text : 'BẢNG GIÁ'
                color : 255/255, 255/255, 255/255, 1
                font_size : self.height * 0.25
            ScaleLabel:
                text : 'HƯỚNG DẪN'
                color : 255/255, 255/255, 255/255, 1
                font_size : self.height * 0.25
            Button_Sign_In:
                name : 'login_button'
                source: "img//button_login.png"
                size_hint_x : 0.9   
            Widget:
                size_hint_x : 0.1
        MDBoxLayout:
            size_hint_y : 0.8
            MDFloatLayout:
                Image:
                    source : 'img//welcome_1.png'
                    size_hint_x : 0.7
                    pos_hint : {'x' : 0.4 }
                    color: 255/255, 255/255, 255/255 , 1
                ScaleLabel:
                    text : 'Ứng Dụng'
                    font_size : self.height * 0.04
                    pos_hint : {'x' : 0.1, 'y' : 0.18}
                    color: 255/255, 255/255, 255/255 , 1
                    size_hint_x : 0.2
                ScaleLabel:
                    text : 'QUẢN LÝ BÁN HÀNG'
                    font_size : self.height * 0.05
                    pos_hint : {'x' : 0.1 , 'y' : 0.10}
                    color: 255/255, 255/255, 255/255 , 1
                    size_hint_x : 0.3
                    font_name:"font//Nunito//Nunito-Bold.ttf"
                ScaleLabel:
                    text : 'Công cụ giúp bạn quản lý thật nhanh và đơn giản các kênh bán hàng thương mại điện tử như Shopee, Lazada, Tiki, Sendo ...'
                    pos_hint : {'x' : 0.1 , 'y' : 0.01}
                    font_size : self.height * 0.02
                    color: 255/255, 255/255, 255/255 , 1
                    size_hint_x : 0.4
                Button_Sign_Up:
                    name : 'login_button'
                    source: "img//button_login_1.png"
                    size_hint : (0.2 , 0.1)
                    pos_hint : {'center_x' : 0.25 , 'center_y' : 0.39}

<CreateUserScreen>
    name : 'createuserscreen'
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'img//bg_login_v1.png'
    orientation : 'vertical'
    MDBoxLayout:
        orientation : 'vertical'
    ScaleLabel:
        text : 'ĐĂNG KÝ'
        color: 255/255, 255/255, 255/255 , 1
        font_size : self.height * 0.06
        halign : 'center'
        pos_hint : {'center_x' : 0.5, 'center_y' : 0.85}
        font_name:"font//Nunito//Nunito-Bold.ttf"
        size_hint_x : 0.3
    MDTextFieldRound:
        id : username_create
        max_text_length: 20
        font_size : '20sp'
        pos_hint : {'center_x' : 0.5 , 'center_y' : 0.75}
        size_hint : (0.5,0.06)
        hint_text : 'Tên đăng nhập của bạn'
        helper_text : 'Thông tin bắt buộc'
        helper_text_mode : 'on_error'
        icon_right : 'account'
        icon_color : app.theme_cls.primary_color
        required : True
        mode: "rectangle"
        normal_color : 255, 255, 255, 1
        color_active: 237/255, 237/255, 237/255, 1
        font_name:"font//Nunito//Nunito-SemiBold.ttf"
        write_tab: False
        multiline: False


    MDTextFieldRound:
        id : password_create
        max_text_length: 20
        font_size : '20sp'
        pos_hint : {'center_x' : 0.5 , 'center_y' : 0.65}
        size_hint : (0.5,0.06)
        hint_text : 'Mật khẩu của bạn'
        helper_text : 'Thông tin bắt buộc'
        helper_text_mode : 'on_error'
        icon_right : 'onepassword'
        icon_color : app.theme_cls.primary_color
        required : True
        password: True
        mode: "rectangle"
        normal_color : 255, 255, 255, 1
        color_active: 237/255, 237/255, 237/255, 1
        font_name:"font//Nunito//Nunito-SemiBold.ttf"
        write_tab: False
        multiline: False

    MDTextFieldRound:
        id : email_create
        max_text_length: 50
        font_size : '20sp'
        pos_hint : {'center_x' : 0.5 , 'center_y' : 0.55}
        size_hint : (0.5,0.06)
        hint_text : 'Email'
        helper_text : 'Thông tin bắt buộc'
        helper_text_mode : 'on_error'
        icon_right : 'email'
        icon_color : app.theme_cls.primary_color
        required : True
        mode: "rectangle"
        normal_color : 255, 255, 255, 1
        color_active: 237/255, 237/255, 237/255, 1
        font_name:"font//Nunito//Nunito-SemiBold.ttf"
        write_tab: False
        multiline: False

    MDTextFieldRound:
        id : name_create
        max_text_length: 20
        font_size : '20sp'
        pos_hint : {'center_x' : 0.5 , 'center_y' : 0.45}
        size_hint : (0.5,0.06)
        hint_text : 'Tên hiển thị'
        icon_right : 'face'
        icon_color : app.theme_cls.primary_color
        mode: "rectangle"
        normal_color : 255, 255, 255, 1
        color_active: 237/255, 237/255, 237/255, 1
        font_name:"font//Nunito//Nunito-SemiBold.ttf"
        write_tab: False
        multiline: False
    MDTextFieldRound:
        id : phone_create
        max_text_length: 20
        font_size : '20sp'
        pos_hint : {'center_x' : 0.5 , 'center_y' : 0.35}
        size_hint : (0.5,0.06)
        hint_text : 'Số điện thoại'
        icon_right : 'phone'
        icon_color : app.theme_cls.primary_color
        mode: "rectangle"
        normal_color : 255, 255, 255, 1
        color_active: 237/255, 237/255, 237/255, 1
        font_name:"font//Nunito//Nunito-SemiBold.ttf"
        write_tab: False
        multiline: False
        on_text_validate: app.create_user_database()
    Button_Create_User_Database:
        source: "img//button_login_1.png"
        size_hint : (0.2 , 0.1)
        pos_hint : {'center_x' : 0.5, 'center_y' : 0.2}


    MDFloatingActionButton:
        icon : 'arrow-left'
        md_bg_color : app.theme_cls.primary_color
        user_font_size : '60sp'
        pos_hint : {'center_x' : 0.04 , 'center_y' : 0.07}
        on_press :
            root.manager.current = 'welcomescreen'
            root.manager.transition.direction = 'right'
    # MDFloatingActionButton:
    #     id : disabled_button
    #     disabled : True
    #     icon : 'account-plus'
    #     md_bg_color : app.theme_cls.primary_color
    #     user_font_size : '60sp'
    #     pos_hint : {'center_x' : 0.96 , 'center_y' : 0.07}
    #     on_press :
    #         root.manager.current = 'welcomescreen'
    #         root.manager.transition.direction = 'right'
<SignInScreen>
    name : 'signinscreen'
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'img//bg_login_v1.png'
    orientation : 'vertical'
    MDBoxLayout:
        size_hint_y : 1
        MDFloatLayout:
            MDFloatingActionButton:
                icon : 'arrow-left'
                md_bg_color : app.theme_cls.primary_color
                user_font_size : '60sp'
                pos_hint : {'center_x' : 0.04 , 'center_y' : 0.07}
                on_press :
                    root.manager.current = 'welcomescreen'
                    root.manager.transition.direction = 'right'
            MDFloatingActionButton:
                id : disabled_button
                disabled : True
                icon : 'arrow-right'
                md_bg_color : app.theme_cls.primary_color
                user_font_size : '60sp'
                pos_hint : {'center_x' : 0.96 , 'center_y' : 0.07}
                on_press :
                    root.manager.current = 'welcomescreen'
                    root.manager.transition.direction = 'right'

            ScaleLabel:
                text : 'ĐĂNG NHẬP'
                color: 255/255, 255/255, 255/255 , 1
                font_size : self.height * 0.06
                halign : 'center'
                pos_hint : {'center_x' : 0.5, 'center_y' : 0.85}
                font_name:"font//Nunito//Nunito-Bold.ttf"
                size_hint_x : 0.3
            
            MDTextFieldRound:
                id : username_text_field
                font_size : '20sp'
                pos_hint : {'center_x' : 0.5 , 'center_y' : 0.7}
                size_hint : (0.5,0.06)
                hint_text : 'Tên đăng nhập của bạn'
                helper_text : 'Thông tin bắt buộc'
                helper_text_mode : 'on_error'
                icon_right : 'account'
                icon_color : app.theme_cls.primary_color
                required : True
                mode: "rectangle"
                normal_color : 255, 255, 255, 1
                color_active: 237/255, 237/255, 237/255, 1
                font_name:"font//Nunito//Nunito-SemiBold.ttf"
                write_tab: False
                multiline: False
            MDTextFieldRound:
                id : password_text_field
                font_size : '20sp'
                password : True
                pos_hint : {'center_x' : 0.5 , 'center_y' : 0.6}
                size_hint : (0.5,0.06)
                hint_text : 'Mật khẩu của bạn'
                helper_text : 'Thông tin bắt buộc'
                helper_text_mode : 'on_error'
                icon_right : 'eye-off' 
                icon_color : app.theme_cls.primary_color
                required : True
                mode: "rectangle"
                normal_color : 255, 255, 255, 1
                color_active: 237/255, 237/255, 237/255, 1
                font_name:"font//Nunito//Nunito-SemiBold.ttf"
                write_tab: False
                multiline: False
                on_text_validate:app.sign_in_database()

            MDFlatButton:
                text: "Quên mật khẩu ?"
                text_color: 237/255, 237/255, 237/255, 1
                font_name:"font//Nunito//Nunito-SemiBold.ttf"
                font_size : '24sp'
                pos_hint : {'center_x' : 0.5 , 'center_y' : 0.53}
                on_release:
                    on_press: app.open_reset_dialog()
            Button_Sign_In_Database:
                pos_hint : {'center_x' : 0.5 , 'center_y' : 0.45}
                size_hint : ( 0.2 , 0.1)
                source: "img//button_login.png"
            # Button_Reset_User_Password:
            #     pos_hint : {'center_x' : 0.60 , 'center_y' : 0.45}
            #     size_hint : ( 0.2 , 0.1)
            #     source: "img//button_cre.png"

<DashBoardScreen>
    name : 'dashboardscreen'
    # canvas.before:
    #     Rectangle:
    #         pos: self.pos
    #         size: self.size
    #         source: 'img//bg_login_v1.png'
    md_bg_color: 240/255, 240/255, 240/255, 1
    MDBoxLayout:
        # spacing : 20
        MDBoxLayout:
            # md_bg_color: 40/255, 40/255, 40/255, 1
            orientation : 'vertical'
            size_hint_x : 0.17
            spacing : 30
            canvas.before:
                Color:
                    rgba : 255/255, 255/255, 255/255, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    # radius : [20]
            Image:
                source : 'logo//logo_long_full_color.png'
                size_hint : ( 0.6 ,0.2)
                pos_hint : {'center_x' : 0.5 , 'center_y' : 0.5}
            MDFillRoundFlatIconButton:
                id: bt_dashboard
                icon: "desktop-mac-dashboard"
                text: ' Trang chủ'
                pos_hint: {'center_x' : 0.5 , 'center_y' : 0.5}
                font_name: "font//Roboto//Roboto-Regular.ttf"
                font_size: '20sp'
                theme_text_color: "Custom"
                text_color: 1/255, 126/255, 230/255, 1
                icon_color: 1/255, 126/255, 230/255, 1
                md_bg_color: 255/255, 255/255, 255/255, 1
                size_hint: ( 0.85 ,0.1)
                active: False
                on_release:
                    x = 'bt_dashboard'
                    app.button_change_color(x)
                    dashboard.current = 'screen_1'
            MDFillRoundFlatIconButton:
                id: bt_boot_items
                icon: "arrow-up"
                text: 'Đẩy sản phẩm'
                pos_hint: {'center_x' : 0.5 , 'center_y' : 0.5}
                font_name: "font//Roboto//Roboto-Regular.ttf"
                font_size: '20sp'
                theme_text_color: "Custom"
                text_color: 10/255, 10/255, 10/255, 1
                icon_color: 10/255, 10/255, 10/255, 1
                md_bg_color: 255/255, 255/255, 255/255, 1
                size_hint: ( 0.85 ,0.1)
                active: False
                on_release:                
                    x = 'bt_boot_items'
                    app.button_change_color(x)
                    dashboard.current = 'screen_2'
            MDFillRoundFlatIconButton:
                id: bt_reply_ratings
                icon: "star"
                text: ' Trả lời đánh giá'
                pos_hint: {'center_x' : 0.5 , 'center_y' : 0.5}
                font_name: "font//Roboto//Roboto-Regular.ttf"
                font_size: '20sp'
                theme_text_color: "Custom"
                text_color: 10/255, 10/255, 10/255, 1
                icon_color: 10/255, 10/255, 10/255, 1
                md_bg_color: 255/255, 255/255, 255/255, 1
                size_hint: ( 0.85 ,0.1)
                active: False
                on_release:
                    x = 'bt_reply_ratings'
                    app.button_change_color(x)
                    dashboard.current = 'reply_ratings_screen'
            MDFillRoundFlatIconButton:
                id: bt_setting
                icon: "database-settings"
                text: ' Cài đặt'
                pos_hint: {'center_x' : 0.5 , 'center_y' : 0.5}
                font_name: "font//Roboto//Roboto-Regular.ttf"
                font_size: '20sp'
                theme_text_color: "Custom"
                text_color: 10/255, 10/255, 10/255, 1
                icon_color: 10/255, 10/255, 10/255, 1
                md_bg_color: 255/255, 255/255, 255/255, 1
                size_hint: ( 0.85 ,0.1)
                active: False
                on_release:
                    x = 'bt_setting'
                    app.button_change_color(x)
                    dashboard.current = 'screen_4'
            # Button_DB:
            #     id: bt_dashboard 
            #     source: "img//bt_dashboard_color.png"
            #     size_hint: ( 0.9 , 0.2)
            #     on_release:
            #         x = 'bt_dashboard'
            #         app.button_change_color(x)
            #         dashboard.current = 'screen_1'
            # Button_DB:
            #     id: bt_boot_items
            #     source: "img//bt_boot_items_white.png"
            #     size_hint: ( 0.9 , 0.2)
            #     on_release:
            #         x = 'bt_boot_items'
            #         app.button_change_color(x)
            #         dashboard.current = 'screen_2'
            # Button_DB:
            #     id: bt_reply_ratings
            #     source: "img//bt_reply_ratings_white.png"
            #     size_hint: ( 0.9 , 0.2)
            #     on_release:
            #         x = 'bt_reply_ratings'
            #         app.button_change_color(x)             
            #         dashboard.current = 'screen_3'
            # Button_DB:
            #     id: bt_setting
            #     source: "img//bt_setting_white.png"
            #     size_hint: ( 0.9 , 0.2)
            #     on_release:
            #         x = 'bt_setting'
            #         app.button_change_color(x) 
            #         dashboard.current = 'screen_4'
            Widget:
                size_hint_y : 1
            # Button_DB_Log_Out:
            #     source: "img//log_out.png"
            #     size_hint: ( 0.7 , 0.2)
            #     on_release:
            #         # dashboard.current = 'screen_4' ShaderTransition
            #         root.manager.current = 'welcomescreen'
            #         root.manager.transition = FadeTransition()
            
        MDBoxLayout:

            orientation : 'vertical'
            md_bg_color: 230/255, 230/255, 230/255, 1
            padding: 15
            spacing: 15
            MDBoxLayout:
                padding: (30,0,10,0)
                # md_bg_color: 255/255, 255/255, 255/255, 1
                size_hint_y : 0.1
                canvas.before: 
                    Color:
                        rgba : 255/255, 255/255, 255/255, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius : [12]
                            
                ScaleLabel:
                    id: title_dashboard
                    text: "TRANG CHỦ"
                    font_name: "font//Nunito//Nunito-Bold.ttf"
                    font_size: self.height * 0.30
                    color: 50/255, 50/255, 50/255 , 1
                    size_hint_x : 0.8
                    halign : 'left'




                ScaleLabel:
                    text : "Hi Quang"
                    # font_name: "font//Nunito//Nunito-SemiBold.ttf"
                    # pos_hint: {'x' : 0.8 , 'right_y' :0.5}
                    font_size: self.height * 0.24
                    color: 50/255, 50/255, 50/255 , 1
                    size_hint_x : 0.1
                    halign : 'right'

                Button_DB_Log_Out:
                    id: dropdown_item
                    source: "img//teamwork.png"
                    size_hint: ( 0.1 , 0.6)
                    elevation_normal: 12
                    pos_hint: {"center_x": .9, "center_y": .5}
                    on_release: 
                        root.menu.open()

            MDBoxLayout:
                canvas.before: 
                    Color:
                        rgba : 255/255, 255/255, 255/255, 1
                    RoundedRectangle:
                        size: self.size
                        pos: self.pos
                        radius : [12]
                ScreenManager:
                    id : dashboard
                    transition : NoTransition()
                    Screen_1:
                    Screen_2:
                    Reply_Ratings_Screen:
                    Screen_4:
<Screen_1>:
    name: 'screen_1' 
    md_bg_color: 255/255, 255/255, 255/255, 1
    
<Screen_2>:
    name: 'screen_2' 
    md_bg_color: 255/255, 255/255, 255/255, 1

<Reply_Ratings_Screen>:
    name: 'reply_ratings_screen' 
    md_bg_color: 255/255, 255/255, 255/255, 1
    padding: 5
    MDBoxLayout:
        orientation: "vertical"
        padding: (0,10,0,10)
        MDBoxLayout: #box 1
            orientation: "vertical"
            size_hint_y: 0.7
            MDBoxLayout: #Box title
                orientation: "vertical"
                size_hint_y: 0.1
                padding: (30,0,10,0)
                ScaleLabel:
                    text: "Thông tin đánh giá"
                    font_name: "font//Nunito//Nunito-SemiBold.ttf"
                    # pos_hint: {'x' : 0.8 , 'right_y' :0.5}
                    font_size: self.height * 0.55
                    color: 60/255, 60/255, 60/255 , 1
                    halign : 'left'
            MDBoxLayout:
                orientation: "vertical"
                padding: (50,10,50,0)
                MDGridLayout:
                    cols: 2
                    row_force_default: True
                    row_default_height: 100
                    spacing : 20
                    MDLabel:
                        text: 'Đánh giá 5 sao :'
                        size_hint_x : None
                        width: 200
                        font_name: "font//Nunito//Nunito-SemiBold.ttf"
                        font_size: self.height * 0.2
                    MDTextField:
                        hint_text: "Đây là nội dung đánh giá cho các đánh giá 5 sao"
                        mode: "rectangle"
                        size_hint_y : 0.7
                        multiline: True
                        max_text_length: 500
                        color_mode: 'custom'
                        # line_color_focus: 1/255, 126/255, 230/255, 1
                        normal_color: 1/255, 126/255, 230/255, 1
                    MDLabel:
                        text: 'Đánh giá 4 sao :'
                        size_hint_x : None
                        width: 200
                        font_name: "font//Nunito//Nunito-SemiBold.ttf"
                        font_size: self.height * 0.2
                    MDTextField:
                        hint_text: "Đây là nội dung đánh giá cho các đánh giá 4 sao"
                        mode: "rectangle"
                        size_hint_y : 0.7
                        multiline: True
                        max_text_length: 500
                        color_mode: 'custom'
                        line_color_focus: 1/255, 126/255, 230/255, 1
                    MDLabel:
                        text: 'Đánh giá 3 sao :'
                        size_hint_x : None
                        width: 200
                        font_name: "font//Nunito//Nunito-SemiBold.ttf"
                        font_size: self.height * 0.2
                    MDTextField:
                        hint_text: "Đây là nội dung đánh giá cho các đánh giá 3 sao"
                        mode: "rectangle"
                        size_hint_y : 0.7
                        multiline: True
                        max_text_length: 500
                        color_mode: 'custom'
                        line_color_focus: 1/255, 126/255, 230/255, 1
                    MDLabel:
                        text: 'Đánh giá 2 sao :'
                        size_hint_x : None
                        width: 200
                        font_name: "font//Nunito//Nunito-SemiBold.ttf"
                        font_size: self.height * 0.2
                    MDTextField:
                        hint_text: "Đây là nội dung đánh giá cho các đánh giá 2 sao"
                        mode: "rectangle"
                        size_hint_y : 0.7
                        multiline: True
                        max_text_length: 500
                        color_mode: 'custom'
                        line_color_focus: 1/255, 126/255, 230/255, 1
                    MDLabel:
                        text: 'Đánh giá 1 sao :'
                        size_hint_x : None
                        width: 200
                        font_name: "font//Nunito//Nunito-SemiBold.ttf"
                        font_size: self.height * 0.2
                    MDTextField:
                        hint_text: "Đây là nội dung đánh giá cho các đánh giá 1 sao"
                        mode: "rectangle"
                        size_hint_y : 0.7
                        multiline: True
                        max_text_length: 500
                        color_mode: 'custom'
                        line_color_focus: 1/255, 126/255, 230/255, 1
        MDBoxLayout: #box 2
            orientation: "vertical"
            size_hint_y: 0.2
            MDBoxLayout: 
                orientation: "vertical"
                size_hint_y: 0.6
                padding: (30,20,10,0)
                ScaleLabel:
                    text: "Cài đặt"
                    font_name: "font//Nunito//Nunito-SemiBold.ttf"
                    # pos_hint: {'x' : 0.8 , 'right_y' :0.5}
                    font_size: self.height * 0.60
                    color: 60/255, 60/255, 60/255 , 1
                    halign : 'left'
            MDBoxLayout:
                orientation: "vertical"
                padding: (50,10,50,0)
                MDBoxLayout:
                    MDBoxLayout:
                        MDFloatLayout:
                            MDLabel:
                                text: "Tự động trả lời"
                                font_name: "font//Nunito//Nunito-Regular.ttf"
                                pos_hint: {'center_x' : 0.5 , 'center_y' :0.5}
                                font_size: 22
                                color: 60/255, 60/255, 60/255 , 1
                            MDCheckbox:
                                size_hint: None, None
                                size: "48dp", "48dp"
                                pos_hint: {'center_x' : 0.3 , 'center_y' :0.5}

                    MDBoxLayout:
                        MDLabel:
                            text: "Thời gian trả lời"
                            font_name: "font//Nunito//Nunito-Regular.ttf"
                            # pos_hint: {'x' : 0.8 , 'right_y' :0.5}
                            font_size: 22
                            color: 60/255, 60/255, 60/255 , 1
                            halign : 'left'
                
        MDBoxLayout:
            size_hint_y: 0.1
            MDFloatLayout:
                MDFillRoundFlatButton:
                    text: 'Lưu'
                    font_name: "font//Nunito//Nunito-SemiBold.ttf"
                    font_size: 34
                    text_color: 255/255, 255/255, 255/255 , 1
                    theme_text_color: "Custom"
                    md_bg_color: 1/255, 126/255, 230/255, 1
                    pos_hint: {'center_x' : 0.4 , 'center_y' :0.5}
                    size_hint: (0.15, 0.68)
                MDFillRoundFlatButton:
                    text: 'Hủy'
                    font_name: "font//Nunito//Nunito-SemiBold.ttf"
                    font_size: 34
                    text_color: 255/255, 255/255, 255/255 , 1
                    theme_text_color: "Custom"
                    md_bg_color: 50/255, 50/255, 50/255, 1
                    pos_hint: {'center_x' : 0.6 , 'center_y' :0.5}
                    size_hint: (0.15, 0.68)


<Screen_4>:
    name: 'screen_4' 
    md_bg_color: 255/255, 255/255, 255/255, 1

<ResetPasswordScreen>:
    name: "resetpasswordscreen"
    orientation: "vertical"
    spacing: "12dp"
    size_hint_y: None
    height:  "400dp"
    MDBoxLayout:
        orientation: "vertical"
        MDBoxLayout:
            ScreenManager:
                id : reset_password_screen
                Reset_Screen_1:
                Reset_Screen_2:
        MDBoxLayout:
            size_hint_y: None
            height: "100dp"
            MDFloatLayout:
                MDFillRoundFlatIconButton:
                    id: bt_resetpass
                    opacity: 0
                    disabled: True
                    icon: "email"
                    text: "ĐẶT LẠI MẬT KHẨU"
                    font_size: "18sp"
                    font_name: "font//Nunito//Nunito-Bold.ttf"
                    pos_hint: {"center_x": .5, "center_y": .7}
                    md_bg_color: 50/255, 137/255, 255/255, 1
                    size_hint: (0.6,0.5)
                    on_release:
                        y = root.set_new_password()
                        if y == True : error_status.text = 'Đã đặt lại mật khẩu thành công'
                MDFillRoundFlatIconButton:
                    id: bt_sendcode
                    opacity: 1
                    disabled: False
                    icon: "email"
                    text: "GỬI MÃ XÁC NHẬN"
                    font_size: "18sp"
                    font_name: "font//Nunito//Nunito-Bold.ttf"
                    pos_hint: {"center_x": .5, "center_y": .7}
                    md_bg_color: 50/255, 137/255, 255/255, 1
                    # increment_width: "200dp"
                    size_hint: (0.6,0.5)
                    on_release:
                        x = root.check_status()
                        if x == True : reset_password_screen.current = 'reset_screen_2' 
                MDLabel:
                    id: error_status
                    text:''
                    halign: 'center'
                    font_name: "font//Nunito//Nunito-Bold.ttf"
                    font_size: "18sp"
                    color: 253/255, 40/255, 40/255 , 1
                    pos_hint: {"center_x": .5, "center_y": .35}
<Reset_Screen_1>:
    name: 'reset_screen_1' 
    MDLabel:
        text:'Vui lòng cung cấp email đăng ký tài khoản. Bạn sẽ nhận được Mã Xác Thực để cài lại mật khẩu'
        halign: 'center'
        font_name: "font//Nunito//Nunito-SemiBold.ttf"
        font_size: "18sp"
        color: 30/255, 30/255, 30/255 , 1
    MDTextField:
        hint_text: "Email đăng ký"
        icon_right: 'email'
<Reset_Screen_2>:
    name: 'reset_screen_2' 
    MDBoxLayout:
        orientation: "vertical" 
        MDLabel:
            text:'MÃ CODE được gửi qua email. Vui lòng check và điền vào ổ MÃ CODE'
            halign: 'center'
            font_name: "font//Nunito//Nunito-Bold.ttf"
            font_size: "18sp"
            color: 253/255, 40/255, 40/255 , 1
        MDTextField:
            hint_text: "Email đăng ký"
            icon_right: 'email'
        MDTextField:
            hint_text: "Mật khẩu mới"
            password: True
            icon_right: 'eye-off'
        MDTextField:
            hint_text: "Xác nhận Mật khẩu mới"
            password: True
            icon_right: 'eye-off'
        MDTextField:
            hint_text: "MÃ CODE "
            icon_right: 'qrcode'

